# Generated by Django 4.0.1 on 2022-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_organizer', '0002_meeting_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='level',
            field=models.CharField(blank=True, choices=[('novice', 'Новичок'), ('novice+', 'Новичок+'), ('junior', 'Джуниор')], max_length=200, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='worktime_from',
            field=models.DateTimeField(verbose_name='Рабочее время, с'),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='worktime_to',
            field=models.DateTimeField(verbose_name='Рабочее время, до'),
        ),
    ]
