# Generated by Django 4.0.1 on 2022-01-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_organizer', '0003_alter_meeting_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='worktime_from',
            field=models.DateTimeField(verbose_name='Рабочее время, с'),
        ),
        migrations.AlterField(
            model_name='student',
            name='worktime_to',
            field=models.DateTimeField(verbose_name='Рабочее время, до'),
        ),
    ]
