# Generated by Django 4.0.1 on 2022-01-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_organizer', '0004_alter_student_worktime_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time_interval',
            field=models.DateTimeField(default=None, verbose_name='Интервал рабочего времени'),
            preserve_default=False,
        ),
    ]
