# Generated by Django 4.0.1 on 2022-01-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_organizer', '0009_alter_student_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='worktime_from',
            field=models.TimeField(verbose_name='Рабочее время, с'),
        ),
        migrations.AlterField(
            model_name='student',
            name='worktime_to',
            field=models.TimeField(verbose_name='Рабочее время, до'),
        ),
    ]
