# Generated by Django 4.0.1 on 2022-01-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_organizer', '0010_alter_student_worktime_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_interval',
            field=models.DateField(blank=True, null=True, verbose_name='Интервал рабочего времени'),
        ),
    ]
