# Generated by Django 4.0.1 on 2022-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_organizer', '0012_alter_student_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='meeting_organizer.Student', verbose_name='Члены команды'),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='worktime_from',
            field=models.TimeField(verbose_name='Рабочее время, с'),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='worktime_to',
            field=models.TimeField(verbose_name='Рабочее время, до'),
        ),
    ]
