# Generated by Django 4.0.1 on 2022-01-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_organizer', '0013_alter_meeting_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID чата в телеграм'),
        ),
        migrations.AlterField(
            model_name='student',
            name='worktime_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Рабочее время, с'),
        ),
        migrations.AlterField(
            model_name='student',
            name='worktime_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Рабочее время, до'),
        ),
    ]
